services:
  app:
    build: .
    volumes :
      - .:/app
    ports:
      [8000:8000]
    container_name: loan_management
    command: >
      sh -c "./wait-for-it.sh db:5432 -- &&
       python manage.py migrate &&   
        python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
  db:
    image: postgres
    volumes: 
      - ./data/db:/var/lib/postgresql/data
    environment: 
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgre_db