# Generated by Django 5.2.6 on 2025-09-21 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('monthly_salary', models.FloatField()),
                ('approved_limit', models.FloatField(default=0)),
                ('current_debt', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanAppllication',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('loan_amount', models.FloatField()),
                ('tenure', models.CharField(max_length=5)),
                ('interest_rate', models.FloatField()),
                ('monthly_payment', models.FloatField()),
                ('emis_paid_on_time', models.CharField()),
                ('date_of_approval', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan_credit.customer')),
            ],
        ),
    ]
