# Generated by Django 5.2.6 on 2025-09-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_credit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
