# Generated by Django 5.2.6 on 2025-09-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_credit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='loanappllication',
            name='loan_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
