# Generated by Django 5.2.6 on 2025-09-21 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_credit', '0004_alter_customer_approved_limit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='monthly_salary',
            new_name='monthly_income',
        ),
    ]
