# Generated by Django 5.2.6 on 2025-09-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_credit', '0005_rename_monthly_salary_customer_monthly_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanappllication',
            name='tenure',
            field=models.IntegerField(),
        ),
    ]
