# Generated by Django 5.2.6 on 2025-09-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_credit', '0006_alter_loanappllication_tenure'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanappllication',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanappllication',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loanappllication',
            name='emis_paid_on_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanappllication',
            name='monthly_payment',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
