# Generated by Django 5.2.6 on 2025-09-22 09:08

import loan_credit.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_credit', '0007_loanappllication_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='loanappllication',
            name='loan_id',
            field=models.IntegerField(default=loan_credit.models.generate_loan_id, primary_key=True, serialize=False),
        ),
    ]
