# Generated by Django 5.2.6 on 2025-09-22 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_credit', '0008_alter_customer_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanappllication',
            old_name='is_approved',
            new_name='loan_approved',
        ),
    ]
