# Generated by Django 5.2.6 on 2025-09-22 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_credit', '0009_rename_is_approved_loanappllication_loan_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanappllication',
            old_name='monthly_payment',
            new_name='monthly_installment',
        ),
    ]
